<html>
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" 
    "http://www.w3.org/TR/html4/strict.dtd">
  <head>
  
   
  </head>
  <body>
<table class="table">
<tr>
    <th>Id</th>
    <th>Descrição</th>
    <th>Data</th>
    <th>&nbsp;</th>
</tr>
  <?php foreach ($despesas as $despesa) : ?>
<tr>    
    <td><?php echo $this->escapeHtml($despesa->id);?></td>
    <td><?php echo $this->escapeHtml($despesa->valdespesa);?></td>
    <td><?php echo $this->escapeHtml($despesa->dtdespesa->format("Y-m-d"));?></td>

    <td>
        <a href="<?php echo $this->url('despesas',
            array('action'=>'index', 'id' => $despesa->id));?>">Edit</a>
        <a href="<?php echo $this->url('despesas',
            array('action'=>'index', 'id' => $despesa->id));?>">Delete</a>
        
    </td>
</tr>
 <?php endforeach; ?>
</table>

   
  </body>
</html>
 


