<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('Controle de Despesas2'); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() .'/js/fooTable-master/css/footable-0.1.css')                
                ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.3.custom/css/redmond/jquery-ui-1.10.3.custom.css')
                ->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css');
        ?>
    <link rel="stylesheet" type="text/css" href="/js/jtable.2.3.0/themes/metro/blue/jtable.css"   />

    <link href="http://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="http://despesas.local/js/jtable.2.3.0/themes/lightcolor/blue/jtable.css" rel="stylesheet" type="text/css" />
	
    <script src="http://code.jquery.com/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
    <script src="http://despesas.local/js/jtable.2.3.0/jquery.jtable.js" type="text/javascript"></script>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/fooTable-master/js/footable.js')
                ->prependFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js')
                ->prependFile('http://code.jquery.com/jquery-1.9.1.js');
        ?>

     <script src="/js/jtable.2.3.0/jquery.jtable.js"     type="text/javascript"></script>


  <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>
    
    
  
        
    </head>
    <body>
     
       
        <div id="wrap">
            <div class="container">
                <div class="page-header">
                    <h1>Controle de Despesas</h1>
                    
                </div>
        <div id="PeopleTableContainer" style="width: 600px;"></div>        
    	
	<script type="text/javascript">

		$(document).ready(function () {

		    //Prepare jTable
			$('#PeopleTableContainer').jtable({
				title: 'Table of people',
				actions: {
					listAction: 'des.php?action=list',
					createAction: 'PersonActions.php?action=create',
					updateAction: 'PersonActions.php?action=update',
					deleteAction: 'PersonActions.php?action=delete'
				},
				fields: {
					PersonId: {
						key: true,
						create: false,
						edit: false,
						list: false
					},
					Name: {
						title: 'Author Name',
						width: '40%'
					},
					Age: {
						title: 'Age',
						width: '20%'
					},
					RecordDate: {
						title: 'Record date',
						width: '30%',
						type: 'date',
						create: false,
						edit: false
					}
				}
			});

			//Load person list from server
			$('#PeopleTableContainer').jtable('load');
                        $('table').footable();

		});

	</script>                
                
                
                <div class="content">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <div id="footer">
            <div class="container">
                <p class="muted credit pull-left">Company <a href="">© 2013</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="http://mss.com.br">mss</a>.</p>
            </div>
        </div>

        <?php echo $this->inlineScript(); ?>
    

    
    </body>
</html>
<?php echo $this->url('despesas', array("action" => "listlancamentos")); ?>,