<html>
  <head>


    <?php    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))          
                ->prependStylesheet($this->basePath() . 'js/jtable.2.3.0/themes/lightcolor/blue/jtable.css')
                ->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css');
     ?>   
    <?php    echo $this->headScript()
                ->prependFile($this->basePath() . 'js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('http://code.jquery.com/jquery-1.9.1.js')
                ->prependFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js')                
                ->prependFile($this->basePath() . 'js/jtable.2.3.0/jquery.jtable.js')
                ->prependFile('http://code.jquery.com/jquery-1.9.1.js')
                ->prependFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js')
                ->prependFile('http://code.jquery.com/jquery-1.9.1.js')
                 ->prependFile($this->basePath() . 'js/jtable.2.3.0/jquery.jtable.js');    
    
    ?>

  </head>
  <body>
	
                <div class="content">
                    <?php echo $this->content; ?>
                    <?php echo $this->inlineScript(); ?>
                </div>
 
  </body>
</html>
