
<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('Controle '); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
       
        <!-- Styles -->  
        <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />
        <link href="http://despesas.local/js/jtable.2.3.0/themes/lightcolor/gray/jtable.min.css" rel="stylesheet" type="text/css" />
        
        <!-- Scripts -->  
        <script src="http://code.jquery.com/jquery-1.9.1.js" type="text/javascript"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
        <script src="http://despesas.local/js/jtable.2.3.0/jquery.jtable.js" type="text/javascript"></script>

        <script>
            $(function() {
                $( "#tabs" ).tabs();

                $( "#datepicker1" ).datepicker({
                        dateFormat: 'dd/mm/yy',
    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
    nextText: 'Próximo',
    prevText: 'Anterior'                                    
                });
                $( "#datepicker2" ).datepicker({
                        dateFormat: 'dd/mm/yy',
    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
    nextText: 'Próximo',
    prevText: 'Anterior'
                });
            });
        </script>  
    <style>
        body
        {
            /*font-size: 14px;*/
        }           
    </style>   
    </head>
    <body>  
        <div id="wrap">
            <div class="container">
                <div class="page-header">
                    <!--h1>Controle de .....</h1>  -->                  
                </div> 
<div id="tabs"><div class="displayTitulo">sysweb... 1.0</div> 
    <div class="litabs">
    <ul> 
        <li id="li1"><a href="#tabs-1">Clientes</a></li>  
        <li id="li2"><a href="#tabs-2">Expediente</a></li>  
        <li id="li3"><a href="#tabs-3">Utilitários</a></li> 
    </ul>
        </div>
                   
                <div class="content">
                    <?php echo $this->content; ?>
                </div>   
                <div id="footer">
                    <div class="container">
                        <p class="muted credit pull-left"> <a href="">©</a></p>
                        <p class="muted credit pull-right"> <a href="http:"></a></p>
                    </div>
                </div>
            </div>
        </div>  
    </body>
</html>
