<div id="PeopleTableContainer" style="width: 600px;"></div>
        <script type="text/javascript">

		$(document).ready(function () {

		    //Prepare jTable
			$('#PeopleTableContainer').jtable({
				title: 'Table of people',
				actions: {
					listAction:   <?php echo $this->url('despesas', array("action" => "listlancamentos")); ?>,
					createAction: <?php echo $this->url('despesas', array("action" => "listlancamentos")); ?>,
					updateAction: <?php echo $this->url('despesas', array("action" => "update")); ?>,
					deleteAction: <?php echo $this->url('despesas', array("action" => "delete")); ?>,
				},
				fields: {
					PersonId: {
						key: true,
						create: false,
						edit: false,
						list: false
					},
					Name: {
						title: 'Author Name',
						width: '40%'
					},
					Age: {
						title: 'Age',
						width: '20%'
					},
					RecordDate: {
						title: 'Record date',
						width: '30%',
						type: 'date',
						create: false,
						edit: false
					}
				}
			});

			//Load person list from server
			$('#PeopleTableContainer').jtable('load');

		});
                </script>
